export const APP_NAME = 'ai-career-platform';

export const FILE_UPLOAD = {
  MAX_SIZE_MB: 10,
  ALLOWED_EXTENSIONS: ['pdf', 'docx', 'png', 'jpg', 'jpeg'],
  MAX_RESUME_VERSIONS: 10,
} as const;

export const AUTH = {
  ACCESS_TOKEN_EXPIRY_HOURS: 1,
  REFRESH_TOKEN_EXPIRY_DAYS: 7,
  MAX_FAILED_ATTEMPTS: 5,
  LOCKOUT_MINUTES: 30,
  MAX_CONCURRENT_SESSIONS: 3,
  INACTIVITY_TIMEOUT_MINUTES: 30,
  VERIFICATION_LINK_EXPIRY_HOURS: 24,
  RESET_LINK_EXPIRY_HOURS: 1,
  PASSWORD_BCRYPT_ROUNDS: 12,
} as const;

export const QUEUE = {
  RESUME_PROCESSING: {
    VISIBILITY_TIMEOUT_SECONDS: 300,
    MESSAGE_RETENTION_DAYS: 14,
    MAX_RECEIVE_COUNT: 3,
  },
  CAREER_GENERATION: {
    VISIBILITY_TIMEOUT_SECONDS: 600,
    MESSAGE_RETENTION_DAYS: 14,
    MAX_RECEIVE_COUNT: 3,
  },
  EMBEDDING_GENERATION: {
    VISIBILITY_TIMEOUT_SECONDS: 300,
    MESSAGE_RETENTION_DAYS: 14,
    MAX_RECEIVE_COUNT: 3,
  },
} as const;

export const DYNAMO_DB = {
  TABLE_NAME: 'ai-career-platform',
  GSI1_NAME: 'GSI1',
  GSI2_NAME: 'GSI2',
} as const;

export const S3_BUCKETS = {
  STAGING: 'staging',
  PRODUCTION: 'production',
  QUARANTINE: 'quarantine',
  ANALYTICS: 'analytics',
  ASSETS: 'assets',
} as const;

export const OPENSEARCH = {
  COLLECTION_NAME: 'ai-career-vectors',
  CAREER_PATHS_INDEX: 'career-paths-index',
  STUDENT_PROFILES_INDEX: 'student-profiles-index',
  VECTOR_DIMENSION: 1536,
} as const;

export const PAGINATION = {
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
} as const;

export const ERROR_CODES = {
  // Client errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',

  // Server errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Business logic errors
  RESUME_TOO_LARGE: 'RESUME_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  RESUME_PROCESSING_FAILED: 'RESUME_PROCESSING_FAILED',
  MAX_VERSIONS_EXCEEDED: 'MAX_VERSIONS_EXCEEDED',
  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;
