import { IAIProvider, AIProviderOptions } from '@ai-career/shared';

export class MockAIAdapter implements IAIProvider {
  async generateText(prompt: string, _options?: AIProviderOptions): Promise<string> {
    console.log(`[MockAI] Generating text for prompt (length: ${prompt.length})`);
    return "This is a mock AI response. In a production environment, this would be generated by OpenAI.";
  }

  async generateJSON<T>(prompt: string, _schema?: any): Promise<T> {
    console.log(`[MockAI] Generating JSON for prompt (length: ${prompt.length})`);
    
    // Mock resume analysis output based on the shared types
    const mockOutput = {
      skills: [
        {
          skillId: '1',
          name: 'React',
          category: 'Frontend',
          proficiency: 'Advanced',
          confidenceScore: 0.95,
          evidenceType: 'Direct',
          source: 'resume',
          sourceReference: 'Worked with React for 3 years',
          recency: 'current',
        }
      ],
      projects: [],
      experience: [],
      education: [],
      certifications: [],
      improvements: [
        {
          id: 'imp-1',
          category: 'keyword',
          priority: 'High',
          title: 'Missing Cloud Skills',
          description: 'Consider adding AWS or Azure keywords if you have experience with them.'
        }
      ]
    };
    
    return mockOutput as T;
  }
}
